spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weeseed?serverTimezone=Asia/Seoul
    username: root
    password: abc123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_insert: true
        order_update: true
        show_sql: true
        format_sql : true
        jdbc:
          batch_size: 1000
  servlet:
    multipart:
      enabled=true
      max-file-size: 500MB
      max-request-size: 500MB
  mqtt:
    broker: tcp://mqtt_broker_ip:1883
upload:
  directory: /home/midas/
sftp:
  host: 192.168.117.79
  port: 22
  user: midas
  password: P@ssw0rd
raspberry:
  pi:
    url: http://192.168.117.79:8000/


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace  #sql 사용시 파라미터를 로그로 남긴다
